/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type {
  ChainLinkControl,
  ChainLinkControlInterface,
} from "../ChainLinkControl";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    name: "chainlinkFeeds",
    outputs: [
      {
        internalType: "uint64",
        name: "deviation",
        type: "uint64",
      },
      {
        internalType: "uint64",
        name: "heartbeat",
        type: "uint64",
      },
      {
        internalType: "uint64",
        name: "decimal",
        type: "uint64",
      },
      {
        internalType: "uint64",
        name: "gap",
        type: "uint64",
      },
      {
        internalType: "address",
        name: "proxy",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b5061012b806100206000396000f3fe6080604052348015600f57600080fd5b506004361060285760003560e01c8063e8c1650014602d575b600080fd5b6086603836600460c9565b600060208190529081526040902080546001909101546001600160401b0380831692600160401b8104821692600160801b8204831692600160c01b909204909116906001600160a01b031685565b604080516001600160401b039687168152948616602086015292851684840152931660608301526001600160a01b03909216608082015290519081900360a00190f35b60006020828403121560d9578081fd5b81356001600160a01b038116811460ee578182fd5b939250505056fea2646970667358221220dcbff8e849ef5b0e2b1e1f56b878cbbce888a7a1da3fd3d934d74bc318c4985364736f6c63430008030033";

export class ChainLinkControl__factory extends ContractFactory {
  constructor(
    ...args: [signer: Signer] | ConstructorParameters<typeof ContractFactory>
  ) {
    if (args.length === 1) {
      super(_abi, _bytecode, args[0]);
    } else {
      super(...args);
    }
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ChainLinkControl> {
    return super.deploy(overrides || {}) as Promise<ChainLinkControl>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): ChainLinkControl {
    return super.attach(address) as ChainLinkControl;
  }
  connect(signer: Signer): ChainLinkControl__factory {
    return super.connect(signer) as ChainLinkControl__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): ChainLinkControlInterface {
    return new utils.Interface(_abi) as ChainLinkControlInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ChainLinkControl {
    return new Contract(address, _abi, signerOrProvider) as ChainLinkControl;
  }
}
